--  Configuration for bbt generated by Alire
pragma Restrictions (No_Elaboration_Code);
pragma Style_Checks (Off);

package Bbt_Config is
   pragma Pure;

   Crate_Version : constant String := "0.0.6";
   Crate_Name : constant String := "bbt";

   Alire_Host_OS : constant String := "linux";

   Alire_Host_Arch : constant String := "x86_64";

   Alire_Host_Distro : constant String := "debian";

   type Build_Profile_Kind is (release, validation, development);
   Build_Profile : constant Build_Profile_Kind := development;

end Bbt_Config;
