-- -----------------------------------------------------------------------------
-- bbt, the black box tester (https://github.com/LionelDraghi/bbt)
-- Author : Lionel Draghi
-- SPDX-License-Identifier: APSL-2.0
-- SPDX-FileCopyrightText: 2024, Lionel Draghi
-- -----------------------------------------------------------------------------

--  with BBT.Output_Writer.Markdown;
--       -- BBT.Output_Writer.Text;
--
--  procedure BBT.Output_Writer.Initialize is
--  begin
--     BBT.Output_Writer.Markdown.Initialize;
--     -- BBT.Output_Writer.Text.Initialize;
--  end BBT.Output_Writer.Initialize;
